<section id="form_section">
    <div id="form_section_inside">
        <div style="position:relative;">
            <div>
                <div id="form" data-func="window_opacity" class="anim_scale animation">                    
                    <header><h2>бесплатная юридическая консультация</h2></header>
                    <?php include ROOT_PATH.'/component/index/view/forms/main_anim.phtml';?>
                </div>
            </div>
            
            <div id="notify">
                <div id="blueline">
                    <a href="#">сообщить О фактах коррупции</a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="content-section">
        <article>
            <header class="title">
                <?=!empty($item["h1"]) ? "<h2>{$item["h1"]}</h2>" : ""?>
            </header>
            <nav id="services-list">
                <?php include ROOT_PATH.'/component/content/view/services/services.list.phtml';?>
            </nav>
        </article>
    </div>
    <div id="maps">
        <header class="title"><h2>нас легко найти</h2></header>
        <div id="map"></div>
    </div>
</section>