<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="content-language" content="ru" />
<meta name="author" content="Новоселецкий Сергей" />

<meta name="description" content="<?= isset($description) ? $description : '' ?>" />
<title><?= isset($title) ? $title : '' ?></title>
<meta name="keywords" content="<?= isset($keywords) ? $keywords : '' ?>" />

<link href="/component/index/css/popup.plugin.css" type="text/css" rel="stylesheet" media="all" />
<link href="/component/index/css/styleForWindow.css" type="text/css" rel="stylesheet" media="all" />

<link href="/component/index/less/core.less" rel="stylesheet/less" type="text/css" />
<link href="/component/index/less/style.less" rel="stylesheet/less" type="text/css"  />

<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="/component/index/js/kernel.js" type="text/javascript"></script>
<script src="/component/index/js/popup.plugin.js" type="text/javascript"></script>
<script src="/component/index/js/less.js" type="text/javascript"></script>
<script src="/component/index/js/AjaxForm.js" type="text/javascript"></script>