<section id='resp'>
    <?php if(isset($responses)) { ?>
        <?php foreach ($responses as $key => $value) { ?>
            <div class="response_section">
                <div class="helper">
                    <div class="inside">
                        <div class="text">
                            <?=WithStr::CuteContentByLength($value["text"], 125)?>
                        </div>
                    </div>
                </div>
                <a class="photo" href="#" style="background:url(/img/responses/<?=$value["number_response"]?>/attachment.jpg)"></a>
                <div class="name"><?=$value["name"]?></div>
            </div>
        <?php } ?>
        
    <?php } ?>
    
</section>