<div id="bg-blue">
    <header class="titlul-page"><h2>Услуги:</h2></header>

    <aside id="left-col">
        <nav id="services-list">
            <?php include 'services/services.list.phtml';?>
        </nav>
        <section id="buttons">
            <a href="#" class="button">Скачать прайс</a>
            <a href="#" class="button like">Мне нравится</a>
        </section>
    </aside>

    <section id="right-col">
        <section id="img-promo-services"></section>
        <?php include 'services/rightcol.phtml'; ?>
    </section>
</div>