<section id="line">
    <div class="content-section">
        <span class="default">Нужна юридическая помошь?</span>
        <span class="phone">8 (918) 66-99-600</span>
        <span class="email">info@zakonipravo.ru</span>
    </div>
</section>
<section id="navigator">
    <div class="content-section">
        <div class="logo">
            <a href="/">На главную</a>
        </div>
        <div class="inform_section">
            <div id="info_block">
                <span id="medium">юридическая помощь</span>
                <span id="small">звоните</span>
                <span id="big"><a href="tel:+7 918 66-99-600">8 (918) 66-99-600</a></span>
            </div>
            <nav>
                <?php include ROOT_PATH.'/component/index/view/navigation/index.phtml';?>
            </nav>
        </div>
    </div>
</section>