<ul>
    <li>
        <a href="/">о нас</a>
    </li>
    <li>
        <a href="<?=app::I()->MakeUrl("news", "index", array("id" => 3))?>">новости</a>
    </li>
    <li>
        <a href="<?=app::I()->MakeUrl("content", "index", array("id" => 5))?>">цены</a>
    </li>
    <li>
        <a href="<?=app::I()->MakeUrl("content", "index", array("id" => 6))?>">услуги</a>
    </li>
    <li>
        <a href="<?=app::I()->MakeUrl("content", "index", array("id" => 8))?>">контакты</a>
    </li>
    <li>
        <a href="<?=app::I()->MakeUrl("responses", "index", array("id" => 9))?>">отзывы</a>
    </li>
</ul>