<?php if (isset($items) && !empty($items)) { ?>
    <ul class="animation anim_list_slidedown">
        <?php foreach ($items as $index => $value) { ?>
            <li>
                <a href="<?= app::I()->MakeUrl("content", "index", array("id" => $value["id"])) ?>">
                    <?= $value["name"] ?>
                </a>
            </li>
        <?php } ?>
    </ul> 

    <?php if (!empty($pagenation)) { ?>
        <?php include ROOT_PATH.'/component/index/view/pagenation/index.phtml'; ?>
    <?php } ?>
<?php } ?>
